export const ROLES = {
  SYSTEM_ADMIN: 'SYSTEM_ADMIN',
  LOAN_OFFICER: 'LOAN_OFFICER',
  ACCOUNTANT: 'ACCOUNTANT',
  BORROWER: 'BORROWER',
  INVESTOR: 'INVESTOR',
} as const;

export type RoleName = (typeof ROLES)[keyof typeof ROLES];

export const LOAN_STATUS = {
  DRAFT: 'DRAFT',
  PENDING_APPROVAL: 'PENDING_APPROVAL',
  APPROVED: 'APPROVED',
  ACTIVE: 'ACTIVE',
  CLOSED: 'CLOSED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED',
  WRITTEN_OFF: 'WRITTEN_OFF',
} as const;

export type LoanStatus = (typeof LOAN_STATUS)[keyof typeof LOAN_STATUS];

export const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  REVERSED: 'REVERSED',
  VOID: 'VOID',
} as const;

export const PAYMENT_METHOD = {
  CASH: 'CASH',
  MPESA: 'MPESA',
  BANK_TRANSFER: 'BANK_TRANSFER',
  CHEQUE: 'CHEQUE',
} as const;

export const INTEREST_METHOD = {
  FLAT: 'FLAT',
  REDUCING_BALANCE: 'REDUCING_BALANCE',
} as const;

export const DURATION_UNIT = {
  WEEK: 'WEEK',
  MONTH: 'MONTH',
} as const;

export const SCHEDULE_STATUS = {
  PENDING: 'PENDING',
  PARTIAL: 'PARTIAL',
  PAID: 'PAID',
  OVERDUE: 'OVERDUE',
} as const;

export const DOCUMENT_TYPE = {
  NATIONAL_ID: 'NATIONAL_ID',
  PASSPORT_PHOTO: 'PASSPORT_PHOTO',
  LOAN_AGREEMENT: 'LOAN_AGREEMENT',
  STATEMENT: 'STATEMENT',
  OTHER: 'OTHER',
} as const;

export const RISK_RATING = {
  LOW: 'LOW',
  STANDARD: 'STANDARD',
  HIGH: 'HIGH',
  BLACKLISTED: 'BLACKLISTED',
} as const;

export const AUDIT_ACTIONS = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  LOGIN_FAILED: 'LOGIN_FAILED',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  USER_DEACTIVATED: 'USER_DEACTIVATED',
  BORROWER_CREATED: 'BORROWER_CREATED',
  BORROWER_UPDATED: 'BORROWER_UPDATED',
  LOAN_CREATED: 'LOAN_CREATED',
  LOAN_UPDATED: 'LOAN_UPDATED',
  LOAN_SUBMITTED: 'LOAN_SUBMITTED',
  LOAN_APPROVED: 'LOAN_APPROVED',
  LOAN_REJECTED: 'LOAN_REJECTED',
  LOAN_ACTIVATED: 'LOAN_ACTIVATED',
  LOAN_CLOSED: 'LOAN_CLOSED',
  LOAN_WRITTEN_OFF: 'LOAN_WRITTEN_OFF',
  PAYMENT_CREATED: 'PAYMENT_CREATED',
  PAYMENT_REVERSED: 'PAYMENT_REVERSED',
  DATA_IMPORTED: 'DATA_IMPORTED',
  DATA_EXPORTED: 'DATA_EXPORTED',
  SETTINGS_CHANGED: 'SETTINGS_CHANGED',
} as const;

export const NOTIFICATION_TYPES = {
  LOAN_SUBMITTED: 'LOAN_SUBMITTED',
  LOAN_APPROVED: 'LOAN_APPROVED',
  LOAN_REJECTED: 'LOAN_REJECTED',
  PAYMENT_RECEIVED: 'PAYMENT_RECEIVED',
  PAYMENT_DUE: 'PAYMENT_DUE',
  PAYMENT_OVERDUE: 'PAYMENT_OVERDUE',
  PASSWORD_RESET: 'PASSWORD_RESET',
} as const;

// Pagination defaults
export const DEFAULT_PAGE = 1;
export const DEFAULT_PER_PAGE = 20;
export const MAX_PER_PAGE = 100;

// Auth constants
export const BCRYPT_SALT_ROUNDS = 12;
export const MAX_LOGIN_ATTEMPTS = 5;
export const LOCKOUT_DURATION_MINUTES = 15;
export const PASSWORD_MIN_LENGTH = 8;

// File upload limits
export const MAX_FILE_SIZE = 5 * 1024 * 1024; // 5MB
export const ALLOWED_FILE_TYPES = [
  'image/jpeg',
  'image/png',
  'image/gif',
  'application/pdf',
];

// Currency
export const DEFAULT_CURRENCY = 'KES';
